Repository celestiaorg/blobstream-contracts, pull requests merged in 2022-03, with the labels that each got.

#33 feat: Add oracle interface
  README.md
  ethereum/solidity/contracts/DataRootTuple.sol
  ethereum/solidity/contracts/IDAOracle.sol
  ethereum/solidity/contracts/QuantumGravityBridge.sol
Labels: enhancement

#32 feat: Add Merkle tree libraries
  README.md
  ethereum/solidity/contracts/DataRootTuple.sol
  ethereum/solidity/contracts/IDAOracle.sol
  ethereum/solidity/contracts/QuantumGravityBridge.sol
  ethereum/solidity/contracts/lib/tree/Constants.sol
  ethereum/solidity/contracts/lib/tree/Utils.sol
  ethereum/solidity/contracts/lib/tree/binary/BinaryMerkleProof.sol
  ethereum/solidity/contracts/lib/tree/binary/BinaryMerkleTree.sol
  ethereum/solidity/contracts/lib/tree/binary/TreeHasher.sol
  ethereum/solidity/contracts/lib/tree/namespace/NamespaceMerkleProof.sol
  ethereum/solidity/contracts/lib/tree/namespace/NamespaceMerkleTree.sol
  ethereum/solidity/contracts/lib/tree/namespace/NamespaceNode.sol
  ethereum/solidity/contracts/lib/tree/namespace/TreeHasher.sol
Labels: enhancement

#70 fix: Use minimum solc v0.8.4
  ethereum/solidity/src/ContextUpgradeable.sol
  ethereum/solidity/src/DataRootTuple.sol
  ethereum/solidity/src/HashingTest.sol
  ethereum/solidity/src/IDAOracle.sol
  ethereum/solidity/src/OwnableUpgradeableWithExpiry.sol
  ethereum/solidity/src/QuantumGravityBridge.sol
  ethereum/solidity/src/TestERC20.sol
  ethereum/solidity/src/lib/tree/Constants.sol
  ethereum/solidity/src/lib/tree/Utils.sol
  ethereum/solidity/src/lib/tree/binary/BinaryMerkleProof.sol
  ethereum/solidity/src/lib/tree/binary/BinaryMerkleTree.sol
  ethereum/solidity/src/lib/tree/binary/TreeHasher.sol
  ethereum/solidity/src/lib/tree/binary/test/BinaryMerkleTree.t.sol
  ethereum/solidity/src/lib/tree/binary/test/TreeHasher.t.sol
  ethereum/solidity/src/lib/tree/namespace/NamespaceMerkleProof.sol
  ethereum/solidity/src/lib/tree/namespace/NamespaceMerkleTree.sol
  ethereum/solidity/src/lib/tree/namespace/NamespaceNode.sol
  ethereum/solidity/src/lib/tree/namespace/TreeHasher.sol
  ethereum/solidity/src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
  ethereum/solidity/src/lib/tree/namespace/test/TreeHasher.t.sol
  ethereum/solidity/src/lib/tree/test/Utils.t.sol
Labels: contracts

#78 chore: Clean up readme.
  README.md
Labels: documentation

#83 feat(ci): run forge test
  .github/workflows/tests.yml
Labels: github_actions

#84 chore: Improve readme.
  README.md
Labels: documentation

#85 chore: Add period at end of comment.
  ethereum/solidity/src/QuantumGravityBridge.sol
Labels: documentation

#92 feat: Refactor and add inner node verification logic.
  ethereum/solidity/src/lib/tree/namespace/NamespaceMerkleTree.sol
  ethereum/solidity/src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
Labels: enhancement, contracts

#95 chore: remove goreleaser
  .github/workflows/release.yml
  .goreleaser.yml
Labels: github_actions

#97 fix: use new nonce instead of current nonce
  ethereum/solidity/src/QuantumGravityBridge.sol
  ethereum/solidity/wrappers/QuantumGravityBridge.sol/wrapper.go
Labels: bug, contracts

#102 chore: add tests for verifyInner
  ethereum/solidity/src/lib/tree/namespace/NamespaceMerkleTree.sol
  ethereum/solidity/src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
Labels: contracts
