Repository celestiaorg/blobstream-contracts, pull requests merged in 2023-11, with the labels that each got.

#252 docs: fix typos
  src/Blobstream.sol
  wrappers/Blobstream.sol/wrapper.go
Labels: chore

#255 feat!: deploy Blobstream at a custom nonce
  src/Blobstream.sol
  src/lib/verifier/test/DAVerifier.t.sol
  src/lib/verifier/test/RollupInclusionProofs.t.sol
  src/test/Blobstream.t.sol
  src/test/BlobstreamBenchmark.t.sol
  wrappers/Blobstream.sol/wrapper.go
Labels: contracts, breaking

#254 fix: off by one slice bug
  src/lib/verifier/DAVerifier.sol
  src/lib/verifier/test/DAVerifier.t.sol
Labels: bug, contracts

#253 feat: merkle tree verifier implementation to support all numbers of leaves
  src/lib/tree/Utils.sol
  src/lib/tree/binary/BinaryMerkleTree.sol
  src/lib/tree/binary/test/BinaryMerkleTree.t.sol
  src/lib/tree/namespace/NamespaceMerkleTree.sol
  wrappers/Blobstream.sol/wrapper.go
Labels: enhancement, audit

#260 chore: bump to v4
  go.mod
Labels: chore
