Repository celestiaorg/blobstream-contracts, pull requests merged in 2023-08, with the labels that each got.

#164 feat: support compute square size from proofs
  src/lib/verifier/DAVerifier.sol
  src/lib/verifier/test/DAVerifier.t.sol
Labels: contracts

#168 feat: add intermediate proof verification in DAVerifier
  src/lib/verifier/DAVerifier.sol
  src/lib/verifier/test/DAVerifier.t.sol
Labels: contracts

#170 chore: fix row root/proof grammar
  src/lib/verifier/DAVerifier.sol
  src/lib/verifier/test/DAVerifier.t.sol
Labels: chore

#169 ci: add labels workflow
  .github/workflows/labels.yml
Labels: github_actions

#171 feat: Increase namespace size
  src/lib/tree/Constants.sol
  src/lib/tree/Types.sol
  src/lib/tree/namespace/test/NamespaceMerkleMultiproof.t.sol
  src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
  src/lib/tree/namespace/test/TreeHasher.t.sol
  src/lib/verifier/test/DAVerifier.t.sol
  wrappers/QuantumGravityBridge.sol/wrapper.go
Labels: contracts

#179 chore: use the same environment as CI
  scripts/Dockerfile_Environment
Labels: chore

#173 docs: update comments on the DAVerifier test to reflect the correct transaction type
  src/lib/verifier/test/DAVerifier.t.sol
Labels: documentation

#184 docs: fix broken link to specs
  README.md
Labels: documentation
