Repository celestiaorg/blobstream-contracts, pull requests merged in 2024-01, with the labels that each got.

#272 chore: forge fmt
  src/lib/tree/binary/BinaryMerkleTree.sol
  src/lib/tree/binary/test/BinaryMerkleTree.t.sol
  src/lib/tree/namespace/test/NamespaceMerkleMultiproof.t.sol
  src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
  src/lib/verifier/DAVerifier.sol
  wrappers/Blobstream.sol/wrapper.go
  wrappers/ERC1967Proxy.sol/wrapper.go
Labels: chore

#274 fix: handle the precondition in path length from key when the number of leaves is <= 1
  src/lib/tree/Utils.sol
  src/lib/tree/binary/test/BinaryMerkleTree.t.sol
  wrappers/Blobstream.sol/wrapper.go
Labels: bug

#279 feat: return error codes in binary merkle tree
  src/Blobstream.sol
  src/lib/tree/binary/BinaryMerkleTree.sol
  src/lib/tree/binary/test/BinaryMerkleTree.t.sol
  src/lib/verifier/DAVerifier.sol
  src/lib/verifier/test/DAVerifier.t.sol
  wrappers/Blobstream.sol/wrapper.go
Labels: enhancement, contracts

#277 fix: edge case namespace merkle tree
  src/lib/tree/namespace/NamespaceMerkleTree.sol
  src/lib/tree/namespace/test/NamespaceMerkleTree.t.sol
Labels: bug, audit

#280 docs: document the unnecessary TODO
  src/lib/tree/namespace/NamespaceMerkleTree.sol
Labels: documentation

#282 chore: rename contributor in code owners
  .github/CODEOWNERS
Labels: chore

#283 chore: rename the dependabot reviewer
  .github/dependabot.yml
Labels: chore
